#!/usr/bin/env bash
# shellcheck disable=SC2086

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    dig ${subdomain}.${domain} | awk '/ANSWER SECTION:/ {getline; print "The subdomain " "'${subdomain}'" " is a " $4 " record and points to " $5}'
}


if [ "$#" -eq 1 ]; then
    get_subdomain_info "$1" "www"
    get_subdomain_info "$1" "lb-01"
    get_subdomain_info "$1" "web-01"
    get_subdomain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    get_subdomain_info "$1" "$2"
fi
