#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend muliro.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 333668-web-01 100.25.165.125:80
        server 333668-web-02 54.234.132.103:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
